name: 🚀 Deploy website to PRD server
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci --legacy-peer-deps && npm run build
      - name: List output files
        run: ls
