name: Deploy website to DEV server
on:
  push:
    branches:
      - feature/*
jobs:
  web-deploy:
    name: Deploy Angular app
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.3'
    - name: Install dependencies from sftp script
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/scripts/send_sftp/requirements.txt
    - name: Build Angular app
      run: |
        node -v
        node .github/scripts/update_version/main.js
        npm ci --legacy-peer-deps
        npm run build
    - name: Replace base href
      run: sed 's/\/alegriacrista/\/alegriacrista\/dev/' dist/alegria-portal/index.html
    - name: Run SFTP script
      run: python ./.github/scripts/send_sftp '${{ vars.HOST_URL }}' '${{ secrets.FTP_USERNAME }}' '${{ secrets.FTP_PASSWORD }}' "dev"
